Remove `boxartguide` command - Replaced with sending `boxart` with no arguments
DS-Homebrew/TWLHelper pull request #24
Opened 2022-02-10 16:37 UTC by YourKalamity

2022-02-10 16:53 UTC, Epicpkmn11 commented
Might be good to do the same thing for `twlsfx` (convert)/`twlbgm` (wiki) and `unlaunch` (convert)/`unlaunchbg` (wiki)

2022-02-10 18:40 UTC, LightSage requested changes

2022-02-10 18:40 UTC, LightSage commented on cogs/convert.py
>          Convert an attachment or linked image to an Unlaunch GIF file
It would be nice if the description got changed to reflect the changes made.

2022-02-10 18:40 UTC, LightSage commented on cogs/convert.py
>          Converts an attached, or linked, audio file to TWiLight Menu's BGM format
The same should be done here

2022-02-11 02:47 UTC, lifehackerhansol approved these changes

2022-02-11 07:57 UTC, NightScript370 commented
....I meant to approve the request, oops

2022-02-11 07:57 UTC, NightScript370 approved these changes

2022-02-11 08:02 UTC, merged